### ISSUE TITLE
为什么导出来是imgs空文件夹呢

### ISSUE THREAD

**Issue by BTCB** [bigxixi/ae2css#5]
mac系统，导出来是imgs空文件夹。
用demo提供的AE文件，导出来正常。

**Comment by bigxixi** [comment]
目前不是所有图层都能导出的，现在只能导出【纯色层】和【图像图层】的「位移、旋转、缩放、透明度」动画，或者【预合成】

**Comment by BTCB** [comment]
是「位移、旋转、缩放、透明度」动画，经过测试，貌似「位移、旋转、缩放、透明度」没合成，就不能导出

**Comment by bigxixi** [comment]
如果放进合成里的话，导出的应该是精灵图动画

**Comment by BTCB** [comment]
我是图形，比如「三角形，四边形，线条等等」(非图片，画的图形)，所以就不能导出，只能导出imgs空文件夹。请问「三角形，四边形，线条等等」算是图像图层吗，怎么操作才能导出呢？

**Comment by bigxixi** [comment]
「三角形，四边形，线条等等」在AE里是叫「形状图层」，这个插件暂时不支持导出哈。我说的图像图层是指用导入的png、jpg作为图层

**Comment by bigxixi** [comment]
如果需要导出「三角形，四边形，线条等等」，建议用lottie的方案

**Comment by BTCB** [comment]
好的，非常感谢
